# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-09 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='numero_mascota',
        ),
    ]
