# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-08 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='fecha',
            new_name='fecha_rescate',
        ),
    ]
